import os
import pandas as pd
import re
from rapidfuzz import process, fuzz
import csv
import unicodedata

lista_escolas_referencia = [
      "JOAO DE ALMEIDA ESCOLA MUNICIPAL",
    "JOSE BONIFACIO DO COUTO",
    "PROFESSORA ORNELLA RITA FERRARI SACILOTTO",
    "NIOMAR APPARECIDA MATTOS GOBBO AMARAL GURGEL PROFA",
    "MARIO PATARRA FRATTINI PROF",
    "JOAO SOLIDARIO PEDROSO PROF",
    "ORESTES ORIS DE ALBUQUERQUE PROF",
    "MURILLO DO AMARAL PROF",
    "AMERICO ALVES",
    "ANTONIA BAPTISTA CALAZANS LUZ PROFA",
    "AMBROSINA DE OLIVEIRA MATTOS PROFA",
    "JOAO PEDRO DO NASCIMENTO PROF",
    "PURCINA ELISA DE ALMEIDA PROFA",
    "CENTRO ATEND SOCIOEDUC AO ADOLESCENTE ARACATUBACI",
    "LUIZ GAMA",
    "VANIOLE DIONYSIO MARQUES PAVAN PROFA",
    "NILCE MAIA SOUTO MELO PROFA",
    "URIAS BRAGA COSTA PROFESSOR",
    "ANTONIA EUGENIA MARTINS PROFA",
    "FLORESTANO LIBUTTI",
    "CENTRO DE ATEND SOCIOEDUC AO ADOLESCENTE DE ARUJA CI",
    "WASHINGTON LUIZ PEREIRA DE SOUZA DR",
    "REPUBLICA DOMINICANA",
    "LEA ROSA MELO ANDREGHETTI PROFA",
    "ANTONIO JOSE DOS SANTOS DOM",
    "CARLOS ALBERTO DE OLIVEIRA PROF",
    "ERNANI RODRIGUES PROF",
    "LACY BONILHA DE SOUZA PROFESSORA",
    "LUIZ MARCARI",
    "AMADOR AGUIAR",
    "MARIO JOAQUIM ESCOBAR DE ANDRADE",
    "REPUBLICA DE CUBA",
    "CAIO PRADO JUNIOR DEPUTADO",
    "TSUYA OHNO KIMURA PROFESSORA",
    "ANTONIO DE PADUA CARDOSO ETEC",
    "DURVAL GUEDES DE AZEVEDO PROF",
    "AZARIAS LEITE",
    "EDUARDO VELHO FILHO PROF",
    "FRAGA MAJOR",
    "MARTA APARECIDA HJERTQUIST BARBOSA PROFA",
    "JOAO DOMINGOS MADEIRA PROFESSOR",
    "PROFESSORA NELLY COLLEONE RAVAGNOLLI",
    "NAERSON MIRANDA PROFESSOR",
    "FRANCISCO DE ASSIS GONCALVES CORONEL",
    "AGOSTINHO GRIGOLETO",
    "MARGARIDA MAIA DE ALMEIDA VIEIRA PROFESSORA",
    "MARIA IZABEL FONTOURA",
    "ISAIAS LUIZ MATIAZZO",
    "HUGO PENTEADO TEIXEIRA",
    "EDUARDO BARNABE DEPUTADO",
    "VALENTINA SILVA DE OLIVEIRA FIGUEIREDO DONA",
    "JAMIL GADIA DEPUTADO",
    "MARIA DE LOURDES BORDINI PROFESSORA",
    "EMILIO JOSE SALIM MONSENHOR DOUTOR",
    "JOAO LOURENCO RODRIGUES PROFESSOR",
    "ELCIO ANTONIO SELMI PROFESSOR",
    "ANIBAL DE FREITAS PROFESSOR",
    "MARIA JANUARIA VAZ TUCCORI PROFESSORA",
    "ANTONIO ALVES BERNARDINO",
    "BASILIO BOSNIAC",
    "SALOMAO JORGE DEPUTADO",
    "DARIO GIOMETTI PROFESSOR",
    "CENTRO ATEND SOCIOED ADOLESC DE CERQUEIRA CESAR IICI",
    "ERNESTO FONSECA DOUTOR",
    "CONCEICAO DA COSTA NEVES DEPUTADA",
    "ERNESTO CAETANO DE SOUZA TENENTE",
    "FERNANDO NOBRE",
    "VINICIUS DE MORAES",
    "JOSE SANTANA DE CASTRO PROF ETEC",
    "CASEMIRO DA ROCHA DR",
    "JARDIM ARCO IRIS",
    "RIOLANDO CANNO PROFESSOR",
    "JORGE FERREIRA",
    "ISAC PEREIRA GARCEZ ENG",
    "JULIETA GUEDES MENDONCA PROFA",
    "CARLOS KOCH DOUTOR",
    "MARIA ANTONIETA MARTINS DE ALMEIDA PROFESSORA",
    "MARIO FRANCISCO DE AMORIM",
    "JOAO ORTIZ RODRIGUES",
    "JARDIM CAMPESTRE",
    "HEMILSON CARLOS MAGRINI PROFESSOR",
    "ANGELA SUELI PONTES DIAS PROFESSORA",
    "NOEMIA GARCIA CICILIATO PROFA",
    "CAETANO PETRAGLIA",
    "CENTRO ATEND SOCIOEDUC AO ADOLESC DE FRANCA CI",
    "JARDIM SILVIA II",
    "AZEVEDO SOARES",
    "DALVA LELLIS GARCIA PRADO PROFA",
    "CARLOS CASTILHO PROFESSOR",
    "ROGERIO LACAZ PROF",
    "PAULO ROLIM LOUREIRO DOM",
    "JARDIM SANTA TEREZINHA",
    "TOMIE OHTAKE",
    "ALBERTO BACAN PROFESSOR",
    "VALDERICE THEREZINHA DA MOTTA CAMPOS MARCHINI PROFESSORA",
    "JARDIM FORTALEZA II",
    "FRANCISCO ANTUNES FILHO",
    "IZABEL FERREIRA DOS SANTOS PROFESSORA DONA BELINHA",
    "WANDA MASCAGNI DE SA PROFESSORA",
    "GENOEFA D AQUINO PACITTI PROFESSORA",
    "ANTONIO VIANA DE SOUZA PROFESSOR",
    "VICTOR CIVITA",
    "LIOMAR FREITAS CAMARA PROFESSORA",
    "ANDRE DONATONI",
    "ASA BRANCA DA SERRA",
    "LEDA FELICE FERREIRA PROFESSORA",
    "PAULO DE CASTRO FERREIRA JUNIOR JORNALISTA",
    "MARIA OLIMPIA DE SOUZA QUEIROZ MACIEL",
    "SOPHIA MARIA JANUARIA AMARAL",
    "ANTONIO FLORENTINO",
    "ERNESTA XAVIER RABELO ORSI PROFA",
    "LUCIANO ARMENTANO",
    "SEBASTIAO FRANCISCO FERRAZ DE ARRUDA PROF",
    "PARQUE PIRATININGA",
    "ESTANCIA PARAISO",
    "CARMEN NETTO DOS SANTOS PROFESSORA",
    "BENEDITA FREIRE DE MACEDO DONA",
    "ANNA CALVO DE GODOY PROFESSORA",
    "MANOEL AUGUSTO VIEIRA NETO DESEMBARGADOR",
    "DOLORES GARCIA PASCHOALIN",
    "JERONIMO DE CAMARGO",
    "JOAQUIM FERREIRA DO AMARAL ETEC",
    "DOMINGOS DE MAGALHAES DOUTOR",
    "ALVARO FRAGA MOREIRA",
    "APARECIDO EUZEBIO TORRES PROFESSOR",
    "MARIA DE ALMEIDA SCHLEDORN PROFESSORA",
    "DEOLINDA COPELLI DE SOUZA LIMA PROFESSORA",
    "PEDRO CELESTINO TONOLLI PROFESSOR",
    "ANTONIO LUIZ DE MORAES PROFESSOR",
    "ALTIMIRA PINKE PROFESSORA",
    "PAULO CHAVES PROFESSOR",
    "LAZARO DUARTE DO PATEO PROFESSOR",
    "PEDRO DE TOLEDO",
    "OCTACILIO DE OLIVEIRA PADRE",
    "ARNOLFO AZEVEDO",
    "FRANCISCO ANTONINO PREFEITO",
    "HERMELINA DE ALBUQUERQUE PASSARELLA PROFA",
    "BENITO MARTINELLI PROF",
    "NELSON CABRINI PROF",
    "HENRIQUE MORATO PROF",
    "MARILENE DE OLIVEIRA ACETTO PROFESSORA",
    "DIVA GOMES DOS SANTOS PROFESSORA",
    "MARTA TERESINHA ROSA PROFESSORA",
    "DOMINGOS BAUER LEITE POETA",
    "NOEMIA DIAS PEROTTI DONA",
    "CENTRO ATEND SOCIOEDUC AO ADOLESCENTE DE MIRASSOL CI",
    "LEONOR DE OLIVEIRA MELLO",
    "BENEDITO DE SOUZA LIMA",
    "NARCISO YAGUE GUIMARAES VEREADOR",
    "AMERICO SUGAI",
    "ALMERINDA RODRIGUES PROFA",
    "LUIZ MARTINI",
    "FRANCISCO ANTONIO GONCALVES",
    "ERNANI CALBUCCI PROF",
    "PROFESSORA MARIA ELOIZA PINHEIRO RAMOS",
    "ETEC PROFESSOR JOSE CARLOS SENO JUNIOR",
    "FRANCISCO BERNARDES FERREIRA COMENDADOR",
    "ANTONIO MARIN",
    "FERNANDO BUONADUCE PROFESSOR",
    "FRANCISCO CASABONA PROFESSOR",
    "AMIM JUNDI ETEC",
    "ORESTES FERREIRA DE TOLEDO",
    "ANCHIETA",
    "JOSE RIBEIRO DE BARROS PROF",
    "LUIZA MARIA BERNARDES NORY PROFESSORA",
    "PORTAL DA JUREIA",
    "MARIA IGNES ARAUJO PAULA SANTOS PROFESSORA",
    "ELZA PECANHA DE GODOY",
    "EDUIR BENEDICTO SCARPARI PROFESSOR",
    "MANASSES EPHRAIN PEREIRA PROFESSOR",
    "ALCIDES GUIDETTI ZAGATTO PROFESSOR",
    "ANIGER FRANCISCO DE MARIA MELILLO DOM",
    "WALDYR DURON JUNIOR ETEC",
    "FRANCO CORONEL",
    "ELISEU JORGE PROFESSOR",
    "ALEXANDRINA SANTIAGO NETTO",
    "ALDEIA TEKOA MIRIM",
    "LAUDELINO FERNANDES DOS SANTOS PROFESSOR",
    "CELESTINA DE CAMPOS TOLEDO TEIXEIRA PROFESSORA",
    "MARIETTA FERRAZ DE ASSUMPCAO PROFESSORA",
    "ORACY MATRICARDI PROF",
    "ANTONIO MARINHO DE CARVALHO FILHO",
    "ANTONIO FERNANDES PROFESSOR",
    "DIOGENES RIBEIRO DE LIMA",
    "GERALDO CORREIA DE CARVALHO DOUTOR",
    "JOAO AUGUSTO DE MELLO PROFESSOR",
    "GLETE DE ALCANTARA PROFESSORA",
    "RAUL FERNANDES CHANCELER",
    "DELCIO BACCARO PROFESSOR",
    "ANTONIO LUCAS",
    "GETULIO LIMA CAPITAO",
    "OLGA CHAKUR FARAH PROFESSORA",
    "MARIA DE LOURDES MAIA FROTA PROFA",
    "LUZIA BARUQUE KIRCHE PROFA",
    "JOAQUIM SIMAO",
    "GABRIELA FREIRE LOBO PROFA",
    "FRANCISCO MOLINA MOLINA ESCOLA ESTADUAL",
    "AMARAL WAGNER",
    "JOSE CARLOS ANTUNES PROFESSOR",
    "LOUIS JOSEPH LEBRET PADRE",
    "JOAQUIM DA FONSECA SARAIVA",
    "BENERALDO DE TOLEDO PIZA PROFESSOR",
    "OSCAVO DE PAULA E SILVA PROFESSOR",
    "ESCOLASTICA ROSA DONA ETEC",
    "LAUDO FERREIRA DE CAMARGO MINISTRO",
    "SANTA DALMOLIN DEMARCHI",
    "ANTONIO CAPUTO",
    "OMAR DONATO BASSANI",
    "JOAO JORGE MARMORATO PROFESSOR",
    "CENTRO DE ATENDSOCIOED AO ADOLESCENTE DE SAO CARLOS CI",
    "SALVADOR RAMOS DE MOURA PROF",
    "ALBERTO ANDALO",
    "VICTOR BRITTO BASTOS PROFESSOR",
    "EDERA IRENE PEREIRA DE OLIVEIRA CARDOSO PROFESSORA",
    "MOABE CURY",
    "ARMANDO D OLIVEIRA COBRA",
    "ZILAH FERREIRA VIAGI PASSARELLI DE CAMPOS PROFESSORA",
    "MARIANINHA QUEIROZ PROFESSORA",
    "JOSE BALTAZAR DE SOUZA",
    "LUIS MAGALHAES DE ARAUJO PROFESSOR",
    "PEDRO BRASIL BANDECCHI PROF",
    "FIDELINO DE FIGUEIREDO PROFESSOR",
    "LIBERATO GROSSI PROF",
    "MANUEL DA NOBREGA PADRE",
    "MARIO ARMINANTE PROF",
    "JARDIM CAPELA IV",
    "BASILIDES DE GODOY PROF ETEC",
    "ITALO BETARELLO",
    "JOAO ERNESTO DE SOUZA CAMPOS PROFESSOR",
    "VICTOR OLIVA PROFESSOR",
    "CEPAM ETEC",
    "JOAO DE DEUS CARDOSO DE MELLO",
    "LUCIANE DO ESPIRITO SANTO PROFA",
    "BRASILIO MACHADO",
    "SATURNINO PEREIRA PROFESSOR",
    "HEIDI ALVES LAZZARINI",
    "ROGER JULES DE CARVALHO MANGE",
    "MANDAQUI ETEC",
    "JARAGUA ESCOLA TECNICA ESTADUAL",
    "OCTAVIO MARCONDES FERRAZ ENGENHEIRO",
    "BRANCA CASTRO CANTO E MELO PROFESSORA",
    "LEONOR QUADROS",
    "MIGUEL HIDALGO",
    "ALBERTO LEVY PROFESSOR",
    "DANIEL PAULO VERANO PONTES PROFESSOR",
    "REPUBLICA ARGENTINA",
    "JAIR TOLEDO XAVIER PROFESSOR",
    "GAVIAO PEIXOTO BRIGADEIRO",
    "RODRIGUES ALVES",
    "LEONEL BRIZOLA",
    "ANNITA GUASTINI EIRAS PROFESSORA",
    "BEATRIZ DE QUADROS LEME PROFESSORA",
    "VICTOR MIGUEL ROMANO PROF",
    "FREDERICO MARIANO",
    "MEXICO",
    "EDSON LUIZ RIBEIRO LUZIA PROFESSOR",
    "JOSE VIEIRA DE MORAES PROF",
    "EXPEDICIONARIO BRASILEIRO",
    "IBRAHIM NOBRE",
    "HELIO MOTTA DOUTOR",
    "ALVARO DE SOUZA LIMA DOUTOR",
    "LOURENCO ZANELATTI",
    "JULIO PESTANA",
    "MELVIN JONES",
    "MARIA JOSE",
    "MIGUEL ROQUE PROFESSOR",
    "WALDEMAR RODRIGUES DA SILVA PASTOR",
    "CLARICE SEIKO IKEDA CHAGAS",
    "AYRES NETO DOUTOR",
    "PAUL HUGON PROF",
    "BLANCA ZWICKER SIMOES PROFESSORA",
    "ALBERTO SALOTTI PROF EE",
    "PEDRO ALEXANDRINO",
    "MIGUEL MALUHY COMENDADOR",
    "ARTHUR CHAGAS JUNIOR PROF",
    "MARIA AUGUSTA DE AVILA PROFA",
    "WASHINGTON ALVES NATEL",
    "SANDRA RODRIGUES DE OLIVEIRA",
    "EUNICE MARQUES MOURA BASTOS PROFA",
    "PARQUE DA JUVENTUDE ETEC",
    "CELIA RIBEIRO LANDIM PROFA",
    "SERGIO DA SILVA NOBREZA PROF",
    "RAUL FONSECA",
    "CAROLINA AUGUSTA DA COSTA GALVAO PROFESSORA",
    "GASTAO STRANG PROFESSOR",
    "WOLNY CARVALHO RAMOS PROFESSOR",
    "MARIA DA CONCEICAO OLIVEIRA COSTA PROFESSORA",
    "JACQUES ORLANDO CAMINHA D AVILA REVERENDO",
    "LUIZ SERGIO CLAUDINO DOS SANTOS DEPUTADO",
    "MARIA THEREZA DA CUNHA PEDROSO PROFESSORA",
    "ALBINO LUIZ CALDAS PROFESSOR",
    "MARIA IMACULADA CERQUEIRA BORHER PROFA",
    "PLACIDO DE PAULA E SILVA",
    "JOSE FRANCO CRAVEIRO",
    "NARCISO PIERONI",
    "IDA YOLANDA LANZONI DE BARROS PROFESSORA",
    "MARIA ROSA CAROLINO DOS SANTOS PROFESSORA",
    "JOAO FRANCESCHINI",
    "ALICE ANTENOR DE SOUZA PROFESSORA",
    "ANDRE RODRIGUES DE ALKIMIN PROFESSOR",
    "RESIDENCIAL BORDON",
    "MARINALVA GIMENES COLOSSAL DA CUNHA",
    "GILBERTO FREYRE",
    "DOMINGOS MIGNONI",
    "ANTONIO INACIO MACIEL",
    "DARIO PACHECO PEDROSO DR ETEC",
    "MARIA MAGDALENA DE OLIVEIRA DONA COTA",
    "ARY DE ALMEIDA SINISGALLI PROF",
    "AMACIO MAZZAROPI",
    "LEA APARECIDA VIEIRA GUEDES",
    "MARIA ALICE ALVES PEREIRA",
    "JOSE CELESTINO ARANHA",
    "JOSE GILBERTO DE OLIVEIRA SOUZA PROFESSOR",
    "ENNY TEREZA LONGO FRACARO PROFA"
]

pasta_dos_arquivos = "Tabela das Escolas de SP"

def normalizar_texto(texto):
    texto = str(texto).upper().strip()
    texto = unicodedata.normalize('NFKD', texto)
    texto = ''.join(c for c in texto if not unicodedata.combining(c))  
    texto = re.sub(r'\s+', ' ', texto)  
    return texto

lista_escolas_referencia_norm = [normalizar_texto(e) for e in lista_escolas_referencia]

def extrair_email(celula):
    if pd.isna(celula):
        return None
    encontrados = re.findall(r'[\w\.-]+@[\w\.-]+\.\w+', str(celula))
    return encontrados[0].lower() if encontrados else None

def validar_email(email):
    if email and email.endswith("@educacao.sp.gov.br"):
        return True
    return False

def encontrar_escola(nome, lista_escolas, limiar=90):
    nome_norm = normalizar_texto(nome)
    resultado = process.extractOne(nome_norm, lista_escolas, scorer=fuzz.partial_ratio)
    if resultado and resultado[1] >= limiar:
        return resultado[0]
    return None

emails_unicos = {}

for arquivo in os.listdir(pasta_dos_arquivos):
    caminho = os.path.join(pasta_dos_arquivos, arquivo)
    
    try:
        print(f"Processando arquivo: {arquivo}")

        if arquivo.endswith('.csv'):
            df = pd.read_csv(
                caminho, 
                encoding='utf-8', 
                engine='python', 
                quoting=csv.QUOTE_NONE, 
                on_bad_lines='skip',
                delimiter=';'
            )
        elif arquivo.endswith('.xlsx'):
            df = pd.read_excel(caminho)
        else:
            print(f"Arquivo ignorado (extensão não suportada): {arquivo}")
            continue
        
        print(f"Colunas encontradas ({len(df.columns)}): {list(df.columns)}")
        
        if df.shape[1] <= 19:
            print(f"Arquivo {arquivo} ignorado porque não tem pelo menos 20 colunas.")
            continue
        
        for idx, linha in df.iterrows():
            escola_raw = linha.iloc[6]
            escola = normalizar_texto(escola_raw)
            email_bruto = linha.iloc[19]
            email = extrair_email(email_bruto)

            escola_correspondida_norm = encontrar_escola(escola, lista_escolas_referencia_norm, limiar=90)

            if escola_correspondida_norm and email and validar_email(email):
                
                idx_ref = lista_escolas_referencia_norm.index(escola_correspondida_norm)
                escola_correspondida = lista_escolas_referencia[idx_ref]

                if escola_correspondida not in emails_unicos:
                    emails_unicos[escola_correspondida] = email
                    print(f"Email adicionado: {escola_correspondida} -> {email} (Origem: {escola_raw})")
            else:
                if idx < 5:  
                    print(f"Linha {idx} descartada: Escola='{escola_raw}', Normalizada='{escola}', Email='{email}', Match='{escola_correspondida_norm}'")

    except Exception as e:
        print(f"Erro ao processar {arquivo}: {e}")

if emails_unicos:
    df_resultado = pd.DataFrame([
        {"Escola": escola, "Email": email}
        for escola, email in emails_unicos.items()
    ])

    df_resultado.to_excel("Lista_de_Emails_SP.xlsx", index=False)
    print("Arquivo 'emails_extraidos.xlsx' salvo com sucesso.")
else:
    print("Nenhum e-mail extraído.")
